---
# Add in the details about the exiftool data per operating system
tools:
  # We want the fully qualified paths and note relative paths
  exiftool:
    # IMPORTANT: For exiftool do not use exiftool(-k).exe, just rename
    # it to ensure it doesn't ask for confirmation on exit during cmd run
    # NOTE: I would recommend using forward slashes for windows paths as well!
    Windows: "D:/work/python_dev/videobreakdown/extras/exiftool-12.40/exiftool.exe"
    Darwin: "/usr/local/bin/exiftool"
  ffmpeg:
    # NOTE: use forward slashes for windows paths!
    Windows: "D:/work/python_dev/videobreakdown/extras/ffmpeg/bin/ffmpeg.exe"
    Darwin: "/usr/local/bin/ffmpeg"

# Exporting pdf size
pdf:
  size: "A4" # We use the standards paper formats or custom list [width, height]
  orientation: "landscape" # This can only be landscape or potrait

# supported extension list
formats: [".mp4", ".mov"]

# What size the thumbnails should be
factor: 0.1 # 1/10th the size of the actual resolution, 1920x1080 will
             # have 480x270 size thumnails

# how many frames you want to get out of the vidoe
framecount: 5

# tags to get
tags:
  default:
    FileSize: Size # Total size of the file in human readable format
    FileType: Format # What file format is this
    CreateDate: Created # What date it was created on
    ImageSize: Resolution # Display resolution of the video
    CompressorID: Encoding # What encoding is used
    VideoFrameRate: FPS # Frame rate of the video
    Duration: Duration # Duration of the video in timecode
  calculated: # We will be multiplying these will be calculated values
              # from the existing inputs
    Frames: [Duration, FPS]
  camera_model: [DeviceManufacturer, Make, MajorBrand]
  camera_specific:
    sony: AcquisitionRecordGroupItemValue
    canon: ColorSpace2

# USE HARDWARE ACCELERATION
# Use only if you know what you are doing and have understanding
# of it. If you have an NVIDIA grpahics card you can use "cuda"
# This will be added as an argument in the data or leave it blank!
hw_accel: "-hwaccel cuda"
