---
# Add in the details about the exiftool data per operating system
tools:
  # We want the fully qualified paths and note relative paths
  exiftool:
    # IMPORTANT: For exiftool do not use exiftool(-k).exe, just rename
    # it to ensure it doesn't ask for confirmation on exit during cmd run
    # NOTE: I would recommend using forward slashes for windows paths as well!
    Windows: "D:/work/python_dev/videobreakdown/extras/exiftool-12.40/exiftool.exe"
    Darwin: "/usr/local/bin/exiftool"
  ffmpeg:
    # NOTE: use forward slashes for windows paths!
    Windows: "D:/work/python_dev/videobreakdown/extras/ffmpeg/bin/ffmpeg.exe"
    Darwin: "/usr/local/bin/ffmpeg"


# supported extension list
formats: [".mp4", ".mov"]

# What size the thumbnails should be
factor: 0.25 # 1/4th the size of the actual resolution, 1920x1080 will
             # have 480x270 size thumnails

# how many frames you want to get out of the vidoe
framecount: 5

# tags to get
tags: 
  default:
    FileName: Name # Name of the file
    FileSize: Size # Total size of the file in human readable format
    FileType: Format # What file format is this
    CreateDate: Created # What date it was created on
    VideoFrameRate: FPS # Frame rate of the video
    DurationValue: Frames # Number of frames in the video
    Duration: Duration # Duration in human readable (eg 19.45 seconds)
    ImageSize: Resolution # Display resolution of the video
    CompressorName: Encoding # What encoding is used
    VideoFormatVideoLayoutAspectRatio: AspectRatio # Is it 16:9 or 3:4 
